// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Data
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FbMonsterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static FbMonsterList GetRootAsFbMonsterList(ByteBuffer _bb) { return GetRootAsFbMonsterList(_bb, new FbMonsterList()); }
  public static FbMonsterList GetRootAsFbMonsterList(ByteBuffer _bb, FbMonsterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool FbMonsterListBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "MDFB"); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbMonsterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Data.FbMonsterData? MonsterList(int j) { int o = __p.__offset(4); return o != 0 ? (Data.FbMonsterData?)(new Data.FbMonsterData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MonsterListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Data.FbMonsterList> CreateFbMonsterList(FlatBufferBuilder builder,
      VectorOffset monster_listOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FbMonsterList.AddMonsterList(builder, monster_listOffset);
    return FbMonsterList.EndFbMonsterList(builder);
  }

  public static void StartFbMonsterList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMonsterList(FlatBufferBuilder builder, VectorOffset monsterListOffset) { builder.AddOffset(0, monsterListOffset.Value, 0); }
  public static VectorOffset CreateMonsterListVector(FlatBufferBuilder builder, Offset<Data.FbMonsterData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMonsterListVectorBlock(FlatBufferBuilder builder, Offset<Data.FbMonsterData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMonsterListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Data.FbMonsterList> EndFbMonsterList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Data.FbMonsterList>(o);
  }
  public static void FinishFbMonsterListBuffer(FlatBufferBuilder builder, Offset<Data.FbMonsterList> offset) { builder.Finish(offset.Value, "MDFB"); }
  public static void FinishSizePrefixedFbMonsterListBuffer(FlatBufferBuilder builder, Offset<Data.FbMonsterList> offset) { builder.FinishSizePrefixed(offset.Value, "MDFB"); }
};


}
