// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Data
{

public enum Hand : sbyte
{
  stone = 0,
  paper = 1,
  scissors = 2,
};


}
